@startuml
hide empty members
'hide circle

!theme plain 
'!theme mono plain none mimeograph
<style>
</style>

title Hierarquia de Classes e suas props

class Node
class Node2D
struct CorpoStats





@enduml